### ISSUE TITLE
Flaky on SM-03

### ISSUE THREAD

**Issue by think-simply** [think-simply/OrangeProject#33]
https://github.com/think-simply/OrangeProject/actions/runs/12499153258/job/34873897038

1) Scenario: SM_03: Edit a provider # src/test/features/admin/configuration/socialMediaAuthen.feature:19
   ✔ Before # src/hooks/hooks.ts:22
   ✔ Given User navigates to page # src/test/steps/admin/userManagement/userStep.ts:6
   ✖ When User creates a new provider with name "initalProvider", provider url "url", client id "123", client secret "secret" # src/test/steps/admin/configuration/socialMediaAuthenStep.ts:13
       locator.waitFor: Timeout 20000ms exceeded.
       Call log:
         - waiting for locator('//div[@class="oxd-toast-container oxd-toast-container--bottom"]//p[text()="Success"]') to be visible

           at SocialMediaPage.createProvider (/home/runner/work/OrangeProject/OrangeProject/src/test/pages/admin/configuration/socialMediaAuthenPage.ts:55:44)
           at async World.<anonymous> (/home/runner/work/OrangeProject/OrangeProject/src/test/steps/admin/configuration/socialMediaAuthenStep.ts:16:5)
   - And User updates a provider "initalProvider" to name "provider2", provider url "url2", client id "1236", client secret "secret2" # src/test/steps/admin/configuration/socialMediaAuthenStep.ts:22
   - Then Provider has been updated to "provider2" # src/test/steps/admin/configuration/socialMediaAuthenStep.ts:27
   - When User removes a provider with name "provider2" # src/test/steps/admin/configuration/socialMediaAuthenStep.ts:31
   - Then Provider "provider2" has been deleted # src/test/steps/admin/configuration/socialMediaAuthenStep.ts:35
   ✔ After # src/hooks/hooks.ts:32

**Comment by AISolutionsMaster** [comment]
issue fixed. Closed
